version: "3"
services:
  db1:
    hostname: db1
    build: ./docker/psql # Specify the path of Dockerfile
    ports:
      - "${DB_1_HOST_SIDE_PORT}:${DB_1_PORT}"
    expose:
      - "${DB_1_PORT}" # Published to another service (container)
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  pgadmin:
    hostname: pgadmin
    build:
      context: ./docker/pgadmin # Specify the path of Dockerfile
      args:
        db_1_service: db1
        db_1_port: ${DB_1_PORT}
        db_1_user: ${DB_USER}
    ports:
      - "${PGADMIN_HOST_SIDE_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - db1
